#!/bin/sh
#-
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 The FreeBSD Foundation
#
# This software was developed by Klara, Inc.
# under sponsorship from the FreeBSD Foundation.
#

: ${ETDUMP:=etdump}
: ${MAKEFS:=makefs}
: ${MKIMG:=mkimg}

: ${MAKEFSARGS:=""}
: ${MKIMGARGS:=""}

if [ -n $REPRODUCIBLE_BUILD ]; then
MKIMGARGS="${MKIMGARGS} -t 1742574909"
MAKEFSARGS="${MAKEFSARGS} -T 1742574909"
fi
