# Makefile.amd64 -- with config changes.
# Copyright 1990 W. Jolitz
#	from FreeBSD: src/sys/conf/Makefile.i386,v 1.255 2002/02/20 23:35:49
#
# Makefile for FreeBSD
#
# This makefile is constructed from a machine description:
#	config machineid
# Most changes should be made in the machine description
#	/sys/amd64/conf/``machineid''
# after which you should do
#	 config machineid
# Generic makefile changes should be made in
#	/sys/conf/Makefile.amd64
# after which config should be rerun for all machines.
#

# Which version of config(8) is required.
%VERSREQ=	600018

STD8X16FONT?=	iso

.if !defined(S)
.if exists(./@/.)
S=	./@
.else
S=	../../..
.endif
.endif
.include "$S/conf/kern.pre.mk"

INCLUDES+= -I$S/contrib/libfdt

.if !empty(DDB_ENABLED) || !empty(DTRACE_ENABLED) || !empty(HWPMC_ENABLED)
CFLAGS+=	-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
.endif

PERTHREAD_SSP_ENABLED!=	grep PERTHREAD_SSP opt_global.h || true ; echo
.if !empty(PERTHREAD_SSP_ENABLED)
. if (${COMPILER_TYPE} == "clang" && ${OSRELDATE} >= 1600019) || \
  ${COMPILER_TYPE} == "gcc"
PCPU_CANARY_OFFSET != grep PC_CANARY assym.inc | cut -f3 | xargs printf "%d"
AMD64_SSP_CFLAGS += -mstack-protector-guard=tls
AMD64_SSP_CFLAGS += -mstack-protector-guard-reg=gs
AMD64_SSP_CFLAGS += -mstack-protector-guard-offset=${PCPU_CANARY_OFFSET}
. else
.  warning "Compiler is too old to support PERTHREAD_SSP"
. endif
CFLAGS += ${AMD64_SSP_CFLAGS}
ARCH_FLAGS += ${AMD64_SSP_CFLAGS}
.endif

%BEFORE_DEPEND

%OBJS

%FILES.c

%FILES.s

%FILES.m

%CLEAN

%RULES

.include "$S/conf/kern.post.mk"
